---
- name: Set Android Studio install facts
  set_fact:
    android_sdk_path: "/home/{{ username }}/Code/Android/Sdk"
    shell_profile: "/home/{{ username }}/.bashrc"
  
- name: Install Android Studio
  become_user: "{{ username }}"
  ansible.builtin.unarchive:
    src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2024.3.2.14/android-studio-2024.3.2.14-linux.tar.gz
    dest: "/home/{{ username }}/Code/"
    remote_src: yes

- name: Ensure ANDROID_HOME is set in .bashrc
  become_user: "{{ username }}"
  lineinfile:
    path: "{{ shell_profile }}"
    line: 'export ANDROID_HOME={{ android_sdk_path }}'
    insertafter: EOF
    state: present

- name: Add Android SDK tools to PATH in .bashrc
  become_user: "{{ username }}"
  lineinfile:
    path: "{{ shell_profile }}"
    line: 'export PATH=$PATH:{{ android_sdk_path }}/emulator:{{ android_sdk_path }}/tools:{{ android_sdk_path }}/tools/bin:{{ android_sdk_path }}/platform-tools'
    insertafter: EOF
    state: present
