---
  ## Install for Fedora
- name: Enable docker repo
  when: ansible_pkg_mgr == "dnf5" or ansible_pkg_mgr == "dnf"
  become: true
  ansible.builtin.command: dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install docker-ce
  when: ansible_pkg_mgr == "dnf5" or ansible_pkg_mgr == "dnf"
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    
  ## Install for Debian/Ubuntu
- name: Install VSCodium
  when: ansible_pkg_mgr == "apt"
  ansible.builtin.apt:
    deb: "https://github.com/VSCodium/vscodium/releases/download/1.99.32846/codium_1.99.32846_amd64.deb"
    allow_unauthenticated: true
    state: present

- name: Setup docker
  become: true
  ansible.builtin.command: "{{ cmd }}"
  loop_control:
    loop_var: cmd
  loop:
    - systemctl enable docker
    - systemctl start docker
#    - usermod -aG docker "{{ username }}"

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true

- name: Reset connection to udpdate user group membership
  meta: reset_connection

