- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes
      changed_when: False

    - name: Install dnf package dependencies
      dnf:
        name:
          - flatpak
          - python3-psutil
          - dconf

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

  tasks:
    - name: Install packages
      include_tasks:
        file: tasks/packages-fedora.yml
        file: tasks/packages-flatpak.yml
        file: tasks/setup-gnome.yml
