- hosts: localhost
  connection: local
  become: tru

  pre-tasks:
    - name: Update repositories
      dnf:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages-fedora.yml
