- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update package cache
      package:
        update_cache: yes
      changed_when: False

    - name: Install package dependencies
      package:
        name:
          - flatpak
          - python3-psutil
          - dconf
          - dbus-tools
          - dbus-daemon
          - unzip

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install requirements
      command:
        cmd: ansible-galaxy install -r requirements.yml
      register: cmdresults

  tasks:
    - name: Install packages
      include_tasks: "{{ task }}"
      loop_control:
        loop_var: task
      loop:
        - tasks/packages-system.yml
        - tasks/packages-flatpak.yml
        - tasks/setup-userprefs.yml
        - tasks/setup-gnome.yml		### Must come last because this will trigger a logout

