---
- hosts: localhost
  connection: local
  become: true
  vars:
    devel: true
    devel_flutter: false
    devel_android: true
    kill_gnome: false

  pre_tasks:
    - name: Update package cache
      package:
        update_cache: yes
      changed_when: False

    - name: Install package dependencies
      package:
        name:
          - flatpak
          - python3-psutil
          - dconf
          - dbus-tools
          - dbus-daemon
          - unzip
          - openssl

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install requirements
      command:
        cmd: ansible-galaxy install -r requirements.yml
      register: cmdresults

  tasks:
    - name: Install packages
      ansible.builtin.include_tasks: "{{ task }}"
      loop_control:
        loop_var: task
      loop:
        - tasks/packages-system.yml
        - tasks/packages-flatpak.yml
        - tasks/setup-userprefs.yml

    - name: Setup dev tooling
      ansible.builtin.include_tasks:
        file: tasks/setup-devel.yml
      when: devel

      ### Must come last because this will trigger a logout
    - name: Setup GNOME              
      ansible.builtin.include_tasks:
        file: tasks/setup-gnome.yml		

    - name: Reboot message
      when: "{{ not kill_gnome|bool }}"
      ansible.builtin.debug:
        msg: "To apply any GNOME changes, either reboot the system or kill gnome using 'sudo killall -3 gnome-shell'"




          
