- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes
      changed_when: False

  tasks:
    - name: Install packages
      include_tasks:
        file: tasks/packages-fedora.yml
