- name: Install flatpak packages
  community.general.flatpak:
    name:
      - org.gnome.Extensions
      - eu.betterbird.Betterbird
      - org.onlyoffice.desktopeditors
      - com.github.muriloventuroso.pdftricks
      - com.vscodium.codium
      - io.github.ungoogled_software.ungoogled_chromium
      - com.ultimaker.cura
      - org.nicotine_plus.Nicotine
      - org.videolan.VLC
      - com.ktechpit.whatsie
      - org.gnome.World.Iotas
    state: present
