---
- name: Install Core Tools
  ansible.builtin.package:
    name:
      - incus
      - dpkg

- name: Install Flatpak Apps
  community.general.flatpak:
    name:
      - com.usebruno.Bruno
      
- name: Install VSCodium
  ansible.builtin.include_tasks:
    file: devel/codium.yml

- name: Setup tooling
  become: true
  ansible.builtin.command: "{{ cmd }}"
  loop_control:
    loop_var: cmd
  loop:
    - usermod -aG incus-admin "{{ username }}"
    - systemctl start incus
    - systemctl enable incus
    - incus admin init --minimal           ## incus must be started before this
    - 

### Optional packages
- name: Install Flutter and dependencies
  ansible.builtin.include_tasks:
    file: devel/flutter.yml
  when: devel_flutter

