---
- block:
    - name: Install dotfiles
      copy:
        src: "{{ item }}"
        dest: "~/"
      with_fileglob:
        - "{{ playbook_dir }}/files/dotfiles/.*"
  become_user: "{{ username }}"
