---
- name: Create Code directory
  ansible.builtin.file:
    path: "/home/{{ username }}/Code"
    state: directory
    mode: '0755'

- name: Install Core Tools
  ansible.builtin.package:
    name:
      - incus
      - dpkg
      - golang
      - virt-viewer

- name: Install Flatpak Apps
  community.general.flatpak:
    name:
      - com.usebruno.Bruno
      
- name: Install VSCodium
  ansible.builtin.include_tasks:
    file: devel/codium.yml

- name: Setup docker
  ansible.builtin.include_tasks:
    file: devel/docker.yml
    
- name: Setup tooling
  become: true
  ansible.builtin.command: "{{ cmd }}"
  loop_control:
    loop_var: cmd
  loop:
    - usermod -aG incus-admin "{{ username }}"
    - systemctl start incus
    - systemctl enable incus
    - incus admin init --minimal           ## incus must be started before this

- name: Set root uid and gid (for incus)
  become: true
  loop_control:
    loop_var: "path"
  loop:
    - /etc/subuid
    - /etc/subgid
  ansible.builtin.lineinfile:
    path: "{{ path }}"
    state: present
    line: "root:1000000:1000000000"
      
### Optional packages
- name: Install Android Studio
  become_user: "{{ username }}"
  ansible.builtin.unarchive:
    src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2024.3.2.14/android-studio-2024.3.2.14-linux.tar.gz
    dest: "/home/{{ username }}/Code/"
    remote_src: yes

- name: Install Flutter and dependencies
  ansible.builtin.include_tasks:
    file: devel/flutter.yml
  when: devel_flutter

