- name: Install GNOME Tweaks app
  dnf:
    name:
      - gnome-tweaks

- name: Install GNOME Extensions app
  community.general.flatpak:
    name:
      - org.gnome.Extensions

- name: Install Extensions
  become: true
  package:
    name:
      - gnome-shell-extension-dash-to-dock

- name: Create list of extensions to be enabled
  set_fact:
    new_extensions:
      - "dock-to-dash@micxgx.gmail.com"

- name: Read values from disabled-extensions
  dconf:
    key: /org/gnome/shell/disabled-extensions
    state: read
  register: current_themes

- name: Check if any of the new extensions are present
  set_fact:
#    any_to_remove_present: "{{ (current_themes.stdout | from_json | intersect(new_extensions)) | length > 0 }}"
    current_themes_list: "{{ current_themes.stdout | from_json }}"
    themes_actually_to_remove: "{{ current_themes_list | intersect(new_extensions) }}"
    any_to_remove_present: "{{ themes_actually_to_remove | length > 0 }}"

- name: Remove the values from disabled-extensions
  set_fact:
    updated_themes: "{{ current_themes_list | difference(new_extensions) }}"
  when: any_to_remove_present

- name: Write updated values to disabled-extensions
  dconf:
    key: /org/gnome/shell/disabled-extensions
    value: "{{ updated_themes }}"
    state: set
  when: any_to_remove_present

- name: Read values from enabled-extensions
  dconf:
    key: /org/gnome/shell/enabled-extensions
    state: read
  register: enabled_extensions

- name: Check which values are NOT already in the array
  set_fact:
#    themes_to_actually_add: "{{ new_extensions | difference(enabled_extensions.stdout | from_json) }}"
    current_themes_list: "{{ enabled_extensions.stdout | from_json }}" # Convert JSON string to list
    themes_to_actually_add: "{{ new_extensions | difference(current_themes_list) }}"
    any_to_add_present: "{{ themes_to_actually_add | length > 0 }}"

- name: Add the values to enabled-extensions (only if they are not already present)
  dconf:
    key: /org/gnome/shell/enabled-extensions
    value: "{{ item }}"
    array_append: yes
  loop: "{{ themes_to_actually_add }}"
  when: any_to_add_present

- name: Configure GNOME
  become_user: jeevan
  dconf: key="/org/gnome/desktop/peripherals/touchpad/tap-to-click" value="true"
  dconf: key="/org/gnome/desktop/peripherals/mouse/natural-scroll" value="true"
  dconf: key="/org/gnome/desktop/wm/preferences/button-layout" value="'appmenu:minimize,maximize,close'"
  dconf: key="/org/gnome/mutter/center-new-windows" value="true"
