- name: Install GNOME Tweaks
  dnf:
    name:
      - gnome-tweaks

- name: Configure GNOME
  become_user: jeevan
  dconf: key="/org/gnome/desktop/peripherals/touchpad/tap-to-click" value="true"
  dconf: key="/org/gnome/desktop/peripherals/mouse/natural-scroll" value="true"
