- name: Install GNOME Tweaks app
  dnf:
    name:
      - gnome-tweaks

- name: Install GNOME Extensions app
  community.general.flatpak:
    name:
      - org.gnome.Extensions

- name: Install Extensions
  become: true
  package:
    name:
      - gnome-shell-extension-dash-to-dock

###############################################

- name: Get the current dconf array value
  dconf:
    key: /org/gnome/shell/enabled-extensions
    state: show
  register: current_themes

- name: Process and use the dconf array value (for adding)
  set_fact:
    current_themes_list: "{{ current_themes.stdout | from_json }}"
    themes_to_actually_add: "{{ themes_to_add | difference(current_themes_list) }}"
    any_to_add_present: "{{ themes_to_actually_add | length > 0 }}"

- name: Add the values to the dconf array (only if they are not already present)
  dconf:
    key: /org/gnome/shell/enabled-extensions
    value: "{{ item }}"
    array_append: yes
  loop: "{{ themes_to_actually_add }}"
  when: any_to_add_present

################################

- name: Get the current dconf array value
  dconf:
    key: /org/gnome/shell/diabled-extensions
    state: show
  register: current_themes_x

- name: Process and use the dconf array value (for removing)
  set_fact:
    current_themes_list: "{{ current_themes_x.stdout | from_json }}" # Get it again, since we modified the array
    themes_actually_to_remove: "{{ current_themes_list | intersect(themes_to_remove) }}"
    any_to_remove_present: "{{ themes_actually_to_remove | length > 0 }}"
    updated_themes: "{{ current_themes_list | difference(themes_to_remove) }}"

- name: Set the dconf array to the updated value (after removal)
  dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "{{ updated_themes }}"
    state: set
  when: any_to_remove_present
      
################## Disabled Extensions ##########


- name: Configure GNOME
  become_user: jeevan
  dconf: key="/org/gnome/desktop/peripherals/touchpad/tap-to-click" value="true"
  dconf: key="/org/gnome/desktop/peripherals/mouse/natural-scroll" value="true"
  dconf: key="/org/gnome/desktop/wm/preferences/button-layout" value="'appmenu:minimize,maximize,close'"
  dconf: key="/org/gnome/mutter/center-new-windows" value="true"
