- name: Install GNOME Tweaks
  dnf:
    name:
      - gnome-tweaks

- name: Install GNOME Extensions
  community.general.flatpak:
    name:
      - org.gnome.Extensions

- name: Configure GNOME
  become_user: jeevan
  dconf: key="/org/gnome/desktop/peripherals/touchpad/tap-to-click" value="true"
  dconf: key="/org/gnome/desktop/peripherals/mouse/natural-scroll" value="true"
  dconf: key="/org/gnome/desktop/wm/preferences/button-layout" value="'appmenu:minimize,maximize,close'"
