---
- name: Install and configure GNOME extensions
  include_role:
    name: PeterMosmans.customize-gnome
  vars:
    gnome_user: "{{ username }}"
    gnome_extensions:
      - id: 307         # dash-to-dock
        enable: "true"
      - id: 1460        # vitals
        enable: "true"
    gnome_dconf:
      - key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
        value: "true"
      - key: /org/gnome/desktop/peripherals/mouse/natural-scroll
        value: "true"
      - key: /org/gnome/desktop/wm/preferences/button-layout
        value: "'appmenu:minimize,maximize,close'"
      - key: /org/gnome/mutter/center-new-windows
        value: "true"
      - key: /org/gnome/mutter/experimental-features
        value: "['scale-monitor-framebuffer']"
      - key: /org/gnome/shell/favorite-apps
        value: "['org.gnome.Nautilus.desktop', 'eu.betterbird.Betterbird.desktop', 'org.mozilla.firefox.desktop', 'com.rtosta.zapzap.desktop', 'org.gnome.World.Iotas.desktop', 'org.gnome.Ptyxis.desktop', 'org.gnome.Software.desktop', 'org.onlyoffice.desktopeditors.desktop', 'com.ultimaker.cura.desktop', 'com.vscodium.codium.desktop', 'org.nicotine_plus.Nicotine.desktop']"

        #### dash-to-dock config
      - key: /org/gnome/shell/extensions/dash-to-dock/dock-position
        value: "'LEFT'"
      - key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
        value: "true"
      - key: /org/gnome/shell/extensions/dash-to-dock/extend-height
        value: "true"
      - key: /org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink
        value: "true"
      - key: /org/gnome/shell/extensions/dash-to-dock/transparency-mode
        value: "'FIXED'"
      - key: /org/gnome/shell/extensions/dash-to-dock/background-opacity
        value: "0.8"
  
        #### vitals config
      - key: /org/gnome/shell/extensions/vitals/hot-sensors
        value: "['_processor_usage_', '_memory_usage_', '__temperature_avg__', '_system_load_5m_']"
      - key: /org/gnome/shell/extensions/vitals/position-in-panel
        value: "1"
 





  
